Name = "Colors"
Version = "0.1.1"
Public = "src/Colors.cpp"

DevDependencies = [
	"Soup.Test@0.1.1",
	"Soup.Test.Assert@0.1.4",
]

	[Tests]
	Source = [
		"test/gen/Main.cpp",
	]
	IncludePaths = [
		"test/",
		"test/gen/",
	]